/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
static yyconst short int yy_accept[263] =
    {   0,
       70,   70,   84,   82,   77,   83,    8,   81,   18,    7,
       19,   29,   20,   21,    5,    3,   27,    4,   28,    6,
       67,   67,   67,   30,   26,   14,   13,   15,   66,   66,
       66,   66,   24,   25,   72,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   22,   82,   23,   11,    0,   76,    9,    0,    0,
       80,   78,   68,   67,   67,   67,   69,   70,   71,   16,
       12,   17,   69,   66,   66,    0,   72,   70,   66,   71,
       66,   66,   66,   66,   66,   66,   66,   38,   66,   66,
       66,   66,   66,   66,   46,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   10,   75,
        0,    0,   78,   68,    0,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   44,   66,   66,   47,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,    0,   79,   73,
       31,   66,   33,   34,   66,   66,   66,   66,   40,   41,
       66,   66,   45,   66,    0,   72,   66,    0,   48,   66,
       64,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   60,   66,   66,    0,    0,    0,    0,   32,
       35,   66,   66,   66,   66,   43,   66,    0,    0,   63,

       66,   66,   51,   66,   66,   66,   66,   66,   66,   58,
       66,    0,   72,   66,    0,   66,   62,    0,   66,   66,
       39,   42,   66,    0,    0,   73,   66,   50,   52,   53,
       54,   55,   56,   66,   66,    0,    0,   66,   74,   66,
       37,   65,    1,    0,    0,   66,   57,   66,    2,   73,
       66,   36,    0,   49,   59,    0,    0,   61,   74,    0,
       74,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   26,   26,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   29,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   27,   43,   44,   45,   46,
       47,   48,   27,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    5,
        1,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1
    } ;

static yyconst short int yy_base[274] =
    {   0,
        0,    0,  397, 1193, 1193, 1193,  362,  379, 1193, 1193,
      350,  322, 1193, 1193, 1193, 1193, 1193, 1193, 1193,   49,
       49,   54,   65, 1193, 1193,  313,  308,  300,   68,   77,
       84,  100, 1193, 1193,    0,  104,  108,  125,  101,  106,
      126,   58,  130,   59,  134,  144,  146,  155,  158,   74,
      160, 1193,  258, 1193, 1193,  307, 1193, 1193,  300,  100,
      292,    0,   44,  190,  204,  209,  195,  215,   61, 1193,
     1193, 1193,  218,  221,  208,  238,    0,  234,  241,  107,
      232,  229,  230,  231,  249,  251,  252,  253,  261,  269,
      272,  273,  281,  284,  292,  293,  302,  304,  313,  316,

      318,  321,  332,  335,  346,  349,  361,  370, 1193, 1193,
      289,   59,    0,  352,  257,  351,  366,  380,  375,  385,
      396,  399,  404,  407,  415,  416,  424,  425,  426,  473,
      500,  502,  503,  504,  518,  519,  528,  520,  530,  538,
      542,  550,  539,  553,  562,  564,  572,  272, 1193,   81,
      567,  581,  576,    0,  584,  592,  595,  596,  604,  607,
      612,  615,  616,  624,  264,  676,  257,  650,  703,  704,
      705,  706,  720,  723,  724,  725,  734,  743,  744,  752,
      754,  762,  809,  836,  837,  219,  137,  537,  133,  838,
      839,  847,  848,  862,  864,    0,  865,  193,  152,  867,

      879,  881,  882,  884,  898,  899,  900,  902,  914,  916,
      919,  188,  966,  169,  654,  993,  995,  142,  996,  998,
        0,  997, 1012,  235,  331,  572, 1013, 1021, 1022, 1023,
     1024, 1032, 1033, 1042, 1044,  364,  180, 1043, 1193, 1054,
     1052, 1062,  378,  787,  887, 1063, 1064, 1079,  141,  932,
     1080, 1081,  185, 1083, 1091, 1121, 1113, 1095,  122,  216,
      106, 1193, 1145, 1150, 1152,   85, 1157, 1162, 1167, 1172,
     1177, 1182, 1187
    } ;

static yyconst short int yy_def[274] =
    {   0,
      262,    1,  262,  262,  262,  262,  262,  263,  262,  262,
      262,  264,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  265,  265,
      265,  265,  262,  262,  266,  265,  265,  265,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,  262,  262,  262,  262,  263,  262,  262,  262,  262,
      267,  268,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  266,  265,   38,  262,  266,  266,   38,  266,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,

       38,   38,   38,   38,   38,   38,   38,   38,  262,  262,
      267,  269,  268,  262,  262,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,  262,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,  270,  262,  262,
       38,   38,   38,  130,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,  271,  262,  130,  271,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,  262,   38,   38,  270,  269,  262,  262,   38,
       38,   38,   38,   38,   38,  130,   38,  272,  271,   38,

       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,  273,  262,  183,  273,   38,   38,  262,   38,   38,
      130,   38,   38,  272,  272,  271,   38,   38,   38,   38,
       38,   38,   38,   38,   38,  273,  273,   38,  262,   38,
       38,   38,  272,  271,  271,   38,   38,   38,  273,  273,
       38,   38,  271,   38,   38,  273,  273,   38,  271,  273,
      273,    0,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262
    } ;

static yyconst short int yy_nxt[1254] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
        4,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       30,   43,   30,   44,   30,   30,   30,   45,   46,   47,
       48,   49,   50,   51,   30,   30,   30,   52,   53,   54,
       61,  114,  114,  114,   63,   62,   64,   65,   66,   63,
      112,   65,   65,   66,   67,  149,   68,   69,   69,   67,
       63,   68,   66,   66,   66,   73,   73,   73,   77,   69,
       67,   75,   75,   74,   77,   77,   77,   76,   75,   75,

       77,   78,   78,   77,   94,   97,   76,   75,  110,   77,
      188,   79,  189,   76,   75,  236,   77,   80,   77,   77,
      107,   77,   77,   77,   80,   77,   77,   77,   81,   76,
       59,  198,   77,   76,   75,   80,   77,   76,   87,   75,
       77,   75,   77,   77,   77,   59,   75,   88,  187,   89,
      236,   90,   75,  149,   76,   82,   83,   77,   84,   75,
       91,  198,  188,   75,  189,   85,   75,   75,   95,   92,
       75,   86,   93,  239,   75,   96,   75,   75,  236,   75,
       75,  100,   98,  226,   75,   99,  101,  102,   75,  236,
       75,   75,   75,   75,  198,   75,  103,  236,   75,  104,

      108,   75,  225,  106,   75,   63,   75,   64,   65,   66,
      105,  250,   67,   67,   67,   67,  259,   68,   69,   63,
       67,   65,   65,   66,   63,  236,   66,   66,   66,   67,
      187,   68,   68,   68,   67,   73,   73,   73,   73,   73,
       73,   75,   68,   73,  225,  243,   74,  261,   75,   80,
       76,   78,   78,   77,   75,  115,  115,  115,   78,   78,
       81,   78,   75,   75,   75,   75,  198,  117,   79,   75,
       75,   75,   75,  198,   75,   75,   75,   75,   75,  116,
      118,   75,  119,  187,   75,   75,   75,   75,  150,   75,
      121,   75,   75,   75,   75,   75,  120,   75,   75,   75,

      112,   75,   75,  112,  122,   75,   75,   75,  110,   75,
      123,   57,   75,   75,   75,   75,  109,   75,   75,  126,
      124,   75,  125,   72,   75,   75,   75,   75,  129,  127,
       75,   71,   75,   75,  128,   75,   70,   75,   75,   75,
      225,  243,   75,  130,   75,  132,   75,  131,   75,   75,
       75,   75,   60,   75,   75,  134,   75,   58,   75,   75,
      137,   75,   75,  133,  136,  139,  135,   75,   75,  114,
      114,  114,   75,  236,  249,   75,  141,  138,   75,   75,
      140,   75,   75,   57,   75,   55,   75,  225,  243,   75,
      143,   75,   75,  142,   75,   75,  262,  151,  144,  152,

      262,   75,  145,   75,  146,  262,   75,   75,   75,  262,
       75,  147,   75,   75,  262,   75,   75,  153,   75,  262,
       75,   75,  262,  154,  262,   75,   75,  262,  262,  157,
      262,   75,   75,  158,  155,  156,   75,   75,  262,   75,
       75,  159,   75,  262,   75,   75,  262,   75,   75,  162,
       75,  160,  161,   75,  262,   75,   75,   75,   75,   75,
      262,   75,   75,  262,   75,   75,   75,  262,  262,  164,
       75,  163,   75,  165,  165,  262,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      166,  166,  166,  165,  165,  165,  165,  165,  167,  167,

      167,  167,  168,  165,  165,  166,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      167,  167,  167,  167,  167,  167,  167,  167,  167,  167,
      165,  165,  165,   75,  262,   75,   75,   75,  171,  169,
       75,  262,   75,   75,   75,  172,   75,  170,   75,   75,
       75,   75,   75,   75,  218,  218,  218,  176,   75,   75,
       75,   75,  262,   75,   75,   75,   75,  174,   75,  173,
       75,   75,   75,  175,   75,   75,   75,  262,   75,   75,
      177,  198,   75,   75,   75,  181,   75,  180,   75,  178,
       75,  262,  179,   75,  182,   75,   75,  184,  183,   75,

       75,  244,   75,  245,   75,   75,  262,   75,   75,   75,
       75,  262,   75,   75,   75,  185,   75,   75,   75,  262,
      262,   75,   75,  190,   75,   75,  262,   75,   75,   75,
       75,  262,   75,  192,  191,   75,   75,   75,   75,  194,
       75,   75,   75,  262,   75,   75,  193,   75,   75,   75,
       75,  262,   75,   75,  262,   75,   75,   75,   75,  198,
      195,   75,   75,  236,   75,  196,  262,  199,  199,  199,
       75,  237,  237,  237,  262,  197,  165,  165,  262,  165,
      165,  165,  165,  165,  165,  198,  165,  165,  165,  165,
      165,  165,  165,  166,  166,  166,  165,  165,  165,  165,

      165,  166,  166,  166,  166,  165,  165,  165,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  165,  165,  165,   75,   75,   75,   75,
      262,  262,  262,   75,   75,   75,   75,  262,  262,   75,
       75,   75,   75,   75,  200,  201,   75,   75,   75,  262,
       75,  204,  262,   75,   75,   75,   75,   75,  202,   75,
       75,  205,  262,  203,   75,  206,   75,   75,  207,  208,
       75,  262,  262,   75,   75,   75,  262,   75,  209,   75,
       75,  262,   75,  262,   75,   75,  198,  262,   75,  210,

       75,  211,   75,  262,  253,  253,  253,  262,   75,  212,
      212,  262,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  213,  213,  213,  212,
      212,  212,  212,  212,  214,  214,  214,  214,  215,  212,
      212,  213,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  214,  214,  212,  212,  212,   75,
       75,   75,   75,  262,  217,  262,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,  216,   75,   75,  262,
      262,  220,  219,   75,   75,   75,  198,   75,   75,  221,

       75,  223,   75,  262,   75,   75,  262,   75,   75,  222,
       75,   75,   75,   75,   75,   75,  244,   75,  245,   75,
      229,   75,   75,  262,   75,   75,  228,   75,   75,  227,
       75,   75,   75,   75,  231,   75,  230,  262,   75,   75,
       75,  236,  233,  262,   75,   75,   75,   75,   75,   75,
      232,  234,   75,  262,   75,  262,   75,  262,  262,   75,
       75,  256,   75,  257,  235,   75,  212,  212,  262,  212,
      212,  212,  212,  212,  212,  236,  212,  212,  212,  212,
      212,  212,  212,  213,  213,  213,  212,  212,  212,  212,
      212,  213,  213,  213,  213,  212,  212,  212,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  212,  212,  212,   75,  262,   75,   75,
       75,   75,  262,   75,  238,   75,   75,   75,   75,   75,
      262,   75,   75,   75,   75,   75,   75,  240,  241,  242,
      246,  262,   75,   75,   75,   75,   75,   75,   75,   75,
      262,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,  262,   75,   75,  262,   75,   75,   75,   75,   75,
      247,  248,   75,   75,   75,   75,  251,   75,   75,   75,
       75,  252,   75,  262,   75,   75,   75,   75,   75,  262,

       75,  262,   75,   75,   75,  262,  262,  262,   75,   75,
       75,  254,   75,   75,   75,  255,   75,  258,  262,   75,
       75,   75,  236,   75,   75,   75,   75,   75,   75,   75,
      236,   75,  262,  262,  262,   75,  262,   75,  260,  260,
      260,   75,  256,  262,  257,   56,  262,   56,   56,   56,
       59,  262,  262,   59,   59,   75,   75,  111,  111,  111,
      111,  111,  113,  262,  113,  113,  113,  148,  148,  148,
      148,  148,  186,  186,  186,  186,  186,  165,  262,  165,
      165,  165,  224,  262,  224,  224,  224,  212,  262,  212,
      212,  212,    3,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262
    } ;

static yyconst short int yy_chk[1254] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       20,   63,   63,   63,   21,   20,   21,   21,   21,   22,
      112,   22,   22,   22,   21,  112,   21,   21,   69,   22,
       23,   22,   23,   23,   23,   29,   29,   29,  266,   69,
       23,   42,   44,   29,   30,   30,   30,   29,   42,   44,

       29,   31,   31,   31,   42,   44,   30,   50,   60,   30,
      150,   31,  150,   31,   50,  261,   31,   32,   32,   32,
       50,   36,   36,   36,   80,   37,   37,   37,   32,   32,
       60,  259,   32,   36,   39,   80,   36,   37,   39,   40,
       37,   39,   38,   38,   38,   60,   40,   39,  187,   40,
      249,   40,   40,  187,   38,   36,   37,   38,   38,   41,
       40,  199,  189,   43,  189,   38,   41,   45,   43,   41,
       43,   38,   41,  218,   45,   43,   43,   46,  214,   47,
       45,   46,   45,  199,   46,   45,   47,   47,   48,  237,
       46,   49,   47,   51,  253,   48,   47,  212,   49,   47,

       51,   48,  198,   49,   49,   64,   51,   64,   64,   64,
       48,  237,   67,   67,   67,   64,  253,   64,   64,   65,
       67,   65,   65,   65,   66,  260,   66,   66,   66,   65,
      186,   65,   68,   68,   66,   73,   73,   73,   74,   74,
       74,   75,   68,   73,  224,  224,   74,  260,   75,   81,
       74,   78,   78,   74,   75,   76,   76,   76,   79,   79,
       81,   78,   82,   83,   84,   81,  167,   83,   79,   82,
       83,   84,   81,  165,   79,   82,   83,   84,   81,   82,
       84,   79,   85,  148,   86,   87,   88,   79,  115,   85,
       87,   86,   87,   88,   89,   85,   86,   86,   87,   88,

      111,   89,   90,   61,   88,   91,   92,   89,   59,   90,
       89,   56,   91,   92,   93,   90,   53,   94,   91,   92,
       90,   93,   91,   28,   94,   95,   96,   93,   96,   93,
       94,   27,   95,   96,   94,   97,   26,   98,   95,   96,
      225,  225,   97,   96,   98,   98,   99,   97,   97,  100,
       98,  101,   12,   99,  102,  100,  100,   11,  101,   99,
      102,  102,  100,   99,  101,  103,  100,  102,  104,  114,
      114,  114,  103,  236,  236,  104,  104,  102,  103,  105,
      103,  104,  106,    8,  116,    7,  105,  243,  243,  106,
      106,  116,  105,  105,  107,  106,    3,  116,  106,  117,

        0,  107,  107,  108,  107,    0,  117,  107,  119,    0,
      108,  108,  117,  118,    0,  119,  108,  118,  120,    0,
      118,  119,    0,  119,    0,  120,  118,    0,    0,  121,
        0,  120,  122,  122,  120,  120,  121,  123,    0,  122,
      124,  123,  121,    0,  123,  122,    0,  124,  125,  126,
      123,  124,  125,  124,    0,  125,  126,  127,  128,  129,
        0,  125,  126,    0,  127,  128,  129,    0,    0,  129,
      127,  128,  129,  130,  130,    0,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,

      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  131,    0,  132,  133,  134,  133,  131,
      131,    0,  132,  133,  134,  134,  131,  132,  132,  133,
      134,  135,  136,  138,  188,  188,  188,  138,  135,  136,
      138,  137,    0,  139,  135,  136,  138,  136,  137,  135,
      139,  140,  143,  137,  137,  141,  139,    0,  140,  143,
      139,  226,  141,  142,  140,  143,  144,  142,  141,  140,
      142,    0,  141,  144,  144,  145,  142,  146,  145,  144,

      151,  226,  145,  226,  146,  147,    0,  151,  145,  153,
      146,    0,  147,  151,  152,  147,  153,  155,  147,    0,
        0,  152,  153,  152,  155,  156,    0,  152,  157,  158,
      155,    0,  156,  156,  155,  157,  158,  159,  156,  158,
      160,  157,  158,    0,  159,  161,  157,  160,  162,  163,
      159,    0,  161,  160,    0,  162,  163,  164,  161,  168,
      161,  162,  163,  215,  164,  162,    0,  168,  168,  168,
      164,  215,  215,  215,    0,  164,  166,  166,    0,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,

      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  169,  170,  171,  172,
        0,    0,    0,  169,  170,  171,  172,    0,    0,  169,
      170,  171,  172,  173,  170,  172,  174,  175,  176,    0,
      173,  175,    0,  174,  175,  176,  173,  177,  173,  174,
      175,  176,    0,  174,  177,  177,  178,  179,  178,  179,
      177,    0,    0,  178,  179,  180,    0,  181,  180,  178,
      179,    0,  180,    0,  181,  182,  244,    0,  180,  181,

      181,  182,  182,    0,  244,  244,  244,    0,  182,  183,
      183,    0,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  184,
      185,  190,  191,    0,  185,    0,  184,  185,  190,  191,
      192,  193,  184,  185,  190,  191,  184,  192,  193,    0,
        0,  193,  192,  192,  193,  194,  245,  195,  197,  194,

      200,  197,  194,    0,  195,  197,    0,  200,  194,  195,
      195,  197,  201,  200,  202,  203,  245,  204,  245,  201,
      204,  202,  203,    0,  204,  201,  202,  202,  203,  201,
      204,  205,  206,  207,  206,  208,  205,    0,  205,  206,
      207,  250,  208,    0,  205,  206,  207,  209,  208,  210,
      207,  209,  211,    0,  209,    0,  210,    0,    0,  211,
      209,  250,  210,  250,  211,  211,  213,  213,    0,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,

      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  213,  213,  213,  213,  213,  216,    0,  217,  219,
      222,  220,    0,  216,  216,  217,  219,  222,  220,  216,
        0,  217,  219,  222,  220,  223,  227,  219,  220,  223,
      227,    0,  223,  227,  228,  229,  230,  231,  223,  227,
        0,  228,  229,  230,  231,  232,  233,  228,  229,  230,
      231,    0,  232,  233,    0,  234,  238,  235,  232,  233,
      234,  235,  234,  238,  235,  241,  238,  240,  234,  238,
      235,  240,  241,    0,  240,  242,  246,  247,  241,    0,

      240,    0,  242,  246,  247,    0,    0,    0,  242,  246,
      247,  246,  248,  251,  252,  248,  254,  251,    0,  248,
      251,  252,  257,  254,  255,  248,  251,  252,  258,  254,
      256,  255,    0,    0,    0,  258,    0,  255,  256,  256,
      256,  258,  257,    0,  257,  263,    0,  263,  263,  263,
      264,    0,    0,  264,  264,  265,  265,  267,  267,  267,
      267,  267,  268,    0,  268,  268,  268,  269,  269,  269,
      269,  269,  270,  270,  270,  270,  270,  271,    0,  271,
      271,  271,  272,    0,  272,  272,  272,  273,    0,  273,
      273,  273,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "AnalisadorLexicoC.l"
#define INITIAL 0
#line 2 "AnalisadorLexicoC.l"

#include<stdio.h>
#include<stdlib.h>
int Upper=0;
int Lower=0;
#line 734 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 19 "AnalisadorLexicoC.l"


#line 888 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 263 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1193 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "AnalisadorLexicoC.l"
{ printf("Funcao com retorno: [%s]\t", yytext) ;};
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "AnalisadorLexicoC.l"
{ printf("Funcao sem retorno: [%s]\t", yytext) ;};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "AnalisadorLexicoC.l"
{ printf("Operador de adicao: [%s]\t" , yytext)	    ;};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "AnalisadorLexicoC.l"
{ printf("Operador de subtracao: [%s]\t", yytext)	    ;};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "AnalisadorLexicoC.l"
{ printf("Operador de multiplicacao: [%s]\t", yytext)	    ;};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "AnalisadorLexicoC.l"
{ printf("Operador de divisao: [%s]\t", yytext)	    ;};
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "AnalisadorLexicoC.l"
{ printf("Operador de modulo: [%s]\t", yytext)	    ;};
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "AnalisadorLexicoC.l"
{ printf("Operador not: [%s]\t", yytext)	    ;};
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "AnalisadorLexicoC.l"
{ printf("Operador and: [%s]\t", yytext)	    ;};
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "AnalisadorLexicoC.l"
{ printf("Operador or: [%s]\t", yytext)	    ;};
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "AnalisadorLexicoC.l"
{ printf("Operador notequal: [%s]\t", yytext)	    ;};
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "AnalisadorLexicoC.l"
{ printf("Operador equal: [%s]\t", yytext)	    ;};
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "AnalisadorLexicoC.l"
{ printf("Operador assign: [%s]\t", yytext)	    ;};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "AnalisadorLexicoC.l"
{ printf("Operador less: [%s]\t", yytext)	    ;};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "AnalisadorLexicoC.l"
{ printf("Operador greater: [%s]\t", yytext)	    ;};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "AnalisadorLexicoC.l"
{ printf("Operador lessequal: [%s]\t", yytext)    ;};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "AnalisadorLexicoC.l"
{ printf("Operador greaterequal: [%s]\t", yytext) ;};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 40 "AnalisadorLexicoC.l"
{ printf("NumberSign: [%s]\t", yytext)	  ;};
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 41 "AnalisadorLexicoC.l"
{ printf("Endereco de memoria: [%s]\t", yytext)  ;};
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 42 "AnalisadorLexicoC.l"
{ printf("Parentese esquerdo: [%s]\t", yytext)	  ;};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 43 "AnalisadorLexicoC.l"
{ printf("Parentese direito: [%s]\t", yytext)	  ;};
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 44 "AnalisadorLexicoC.l"
{ printf("Chave esquerda: [%s]\t", yytext)	  ;};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 45 "AnalisadorLexicoC.l"
{ printf("Chave direita: [%s]\t", yytext)	  ;};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 46 "AnalisadorLexicoC.l"
{ printf("Cochete esquerdo: [%s]\t", yytext)	  ;};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 47 "AnalisadorLexicoC.l"
{ printf("Cochete direito: [%s]\t", yytext)  ;};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 48 "AnalisadorLexicoC.l"
{ printf("Ponto e virdula: [%s]\t", yytext)	  ;};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 49 "AnalisadorLexicoC.l"
{ printf("Virgula: [%s]\t", yytext)	  ;};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 50 "AnalisadorLexicoC.l"
{ printf("Ponto: [%s]\t", yytext)		  ;};
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 51 "AnalisadorLexicoC.l"
{ printf("Aspas simples: [%s]\t", yytext)	  ;};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 52 "AnalisadorLexicoC.l"
{ printf("Dois pontos: [%s]\t", yytext)	  ;};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "AnalisadorLexicoC.l"
{ printf("Keyword auto: [%s]\t", yytext)  ;};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "AnalisadorLexicoC.l"
{ printf("Keyword break: [%s]\t", yytext)  ;};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "AnalisadorLexicoC.l"
{ printf("Keyword case: [%s]\t", yytext)  ;};
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "AnalisadorLexicoC.l"
{ printf("Keyword char: [%s]\t", yytext)  ;};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "AnalisadorLexicoC.l"
{ printf("Keyword const: [%s]\t", yytext)  ;};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "AnalisadorLexicoC.l"
{ printf("Keyword continue: [%s]\t", yytext)  ;};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 60 "AnalisadorLexicoC.l"
{ printf("Keyword default: [%s]\t", yytext)  ;};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 61 "AnalisadorLexicoC.l"
{ printf("Keyword do: [%s]\t", yytext)  ;};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 62 "AnalisadorLexicoC.l"
{ printf("Keyword double: [%s]\t", yytext)  ;};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 63 "AnalisadorLexicoC.l"
{ printf("Keyword else: [%s]\t", yytext)     ;};
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 64 "AnalisadorLexicoC.l"
{ printf("Keyword enum: [%s]\t", yytext)  ;};
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 65 "AnalisadorLexicoC.l"
{ printf("Keyword extern: [%s]\t", yytext)  ;};
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 66 "AnalisadorLexicoC.l"
{ printf("Keyword float: [%s]\t", yytext)  ;};
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 67 "AnalisadorLexicoC.l"
{ printf("Keyword for: [%s]\t", yytext)  ;};
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 68 "AnalisadorLexicoC.l"
{ printf("Keyword goto: [%s]\t", yytext)  ;};
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "AnalisadorLexicoC.l"
{ printf("Keyword if: [%s]\t", yytext)       ;};
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "AnalisadorLexicoC.l"
{ printf("Keyword int: [%s]\t", yytext)  ;};
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "AnalisadorLexicoC.l"
{ printf("Keyword long: [%s]\t", yytext)  ;};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "AnalisadorLexicoC.l"
{ printf("Keyword register: [%s]\t", yytext)  ;};
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "AnalisadorLexicoC.l"
{ printf("Keyword return: [%s]\t", yytext)  ;};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "AnalisadorLexicoC.l"
{ printf("Keyword short: [%s]\t", yytext)  ;};
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "AnalisadorLexicoC.l"
{ printf("Keyword signed: [%s]\t", yytext)  ;};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "AnalisadorLexicoC.l"
{ printf("Keyword sizeof: [%s]\t", yytext)  ;};
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "AnalisadorLexicoC.l"
{ printf("Keyword static: [%s]\t", yytext)  ;};
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "AnalisadorLexicoC.l"
{ printf("Keyword struct: [%s]\t", yytext)  ;};
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 79 "AnalisadorLexicoC.l"
{ printf("Keyword switch: [%s]\t", yytext)  ;};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "AnalisadorLexicoC.l"
{ printf("Keyword typedef: [%s]\t", yytext)  ;};
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 81 "AnalisadorLexicoC.l"
{ printf("Keyword union: [%s]\t", yytext)  ;};
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "AnalisadorLexicoC.l"
{ printf("Keyword unsigned: [%s]\t", yytext)  ;};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 83 "AnalisadorLexicoC.l"
{ printf("Keyword void: [%s]\t", yytext)  ;};
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 84 "AnalisadorLexicoC.l"
{ printf("Keyword volatile: [%s]\t", yytext)  ;};
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 85 "AnalisadorLexicoC.l"
{ printf("Keyword while: [%s]\t", yytext)  ;};
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 86 "AnalisadorLexicoC.l"
{ printf("Keyword print: [%s]\t", yytext)    ;};
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 87 "AnalisadorLexicoC.l"
{ printf("Keyword putc: [%s]\t", yytext)     ;};
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 88 "AnalisadorLexicoC.l"
{ printf("Keyword include: [%s]\t", yytext)  ;};
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 90 "AnalisadorLexicoC.l"
{ printf("Letra(s)/Palavra: [%s]>\t", yytext) ;};
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 91 "AnalisadorLexicoC.l"
{ printf("Integer: [%s]\t", yytext)    ;};
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 92 "AnalisadorLexicoC.l"
{ printf("Real: [%s]\t", yytext) ;};
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 93 "AnalisadorLexicoC.l"
{ printf("Hexadecimal: [%s]\t", yytext) ;};
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 94 "AnalisadorLexicoC.l"
{ printf("Octal: [%s]\t", yytext) ;};
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 95 "AnalisadorLexicoC.l"
{ printf("Binario: [%s]\t", yytext) ;};
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 96 "AnalisadorLexicoC.l"
{ printf("Identificador: [%s]\t", yytext) ;};
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 99 "AnalisadorLexicoC.l"
{ printf("Vetor: [%s]\t", yytext) ;};
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 100 "AnalisadorLexicoC.l"
{ printf("Matriz: [%s]\t", yytext) ;};
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 103 "AnalisadorLexicoC.l"
{ printf("Char: [%s]\t", yytext)	      ;};
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 104 "AnalisadorLexicoC.l"
{ printf("String: [%s]\t", yytext)     ;};
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 106 "AnalisadorLexicoC.l"
{ /* DO NOTHING  */ }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 107 "AnalisadorLexicoC.l"
{ printf("Comentario: [%s]", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 108 "AnalisadorLexicoC.l"
{ printf("Comentario: [%s]", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 109 "AnalisadorLexicoC.l"
{ printf("Comentario indeterminado: [%s]", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 110 "AnalisadorLexicoC.l"
{ printf("Aspas duplas indeterminada: [%s]", yytext)  ; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 111 "AnalisadorLexicoC.l"
{ printf("Caractere desconhecido: [%s]",yytext)   ;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 112 "AnalisadorLexicoC.l"
ECHO;
	YY_BREAK
#line 1386 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 263 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 263 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 262);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 112 "AnalisadorLexicoC.l"


int yywrap()
{
return 1;
}

int main()
{

printf("\nEntre com qualquer valor:\n");


yylex();


return 0;
system("PAUSE");

}
