/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[246] =
    {   0,
       69,   69,   83,   81,   76,   82,    6,   80,   16,    5,
       17,   27,   18,   19,    3,    1,   25,    2,   26,    4,
       66,   66,   66,   28,   24,   12,   11,   13,   65,   65,
       65,   65,   65,   22,   23,   71,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   20,   81,   21,    9,    0,   75,    7,    0,
        0,   79,   77,   67,   66,   66,   66,   68,   69,   70,
       14,   10,   15,   68,   65,   65,    0,   71,   65,   69,
       65,   70,   65,   65,   65,   65,   65,   65,   65,   36,
       65,   65,   65,   65,   65,   65,   44,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
        8,   74,    0,    0,   77,   67,    0,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   42,
       65,   65,   45,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
        0,   78,   72,   65,   29,   65,   31,   32,   65,   65,
       65,   65,   38,   39,   65,   65,   43,   65,   46,   65,
       62,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   58,   65,   65,    0,    0,    0,    0,   65,
       30,   33,   65,   65,   65,   65,   41,   65,   61,   65,

       65,   49,   65,   65,   65,   65,   65,   65,   56,   65,
       65,   60,    0,   65,   65,   65,   37,   40,   65,   65,
       48,   50,   51,   52,   53,   54,   65,   65,   65,   73,
       65,   65,   35,   63,   65,   55,   65,   65,   64,   34,
       47,   57,   59,   65,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   19,
       19,   19,   19,   19,   19,   20,   20,   21,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   26,   27,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   30,
       31,   32,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   28,   44,   45,   46,   47,
       48,   49,   28,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[62] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    4,
        5,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1
    } ;

static yyconst short int yy_base[254] =
    {   0,
        0,    0,  234, 1013, 1013, 1013,  206,  212, 1013, 1013,
      199,  158, 1013, 1013, 1013, 1013, 1013, 1013, 1013,   50,
       50,   55,   67, 1013, 1013,  161,  158,  153,   70,   80,
       90,   97,  116, 1013, 1013,    0,  120,  124,  141,  114,
      122,   77,   30,  144,  145,  146,  162,  160,  163,  171,
      174,  179, 1013,  105, 1013, 1013,  147, 1013, 1013,  139,
      191,  133,    0,  206,  213,  228,  233,  243,   73,  100,
     1013, 1013, 1013,  246,   88,  193,  256,    0,  236,  261,
      263,  102,  259,  251,  267,  262,  277,  279,  282,  281,
      293,  297,  301,  298,  312,  313,  316,  331,  328,  339,

      336,  350,  351,  355,  359,  369,  373,  381,  383,  392,
     1013, 1013,  125,  151,    0,  418,   90,  404,  407,  408,
      409,  412,  423,  424,  428,  438,  443,  448,  446,  457,
      458,  462,  460,  474,  476,  477,  478,  492,  493,  502,
      494,  504,  512,  516,  524,  513,  527,  536,  538,  546,
      101, 1013,   72,  541,  550,  555,  560,  565,  569,  577,
      574,  588,  589,  593,  597,  607,  608,  609,  618,  619,
      628,  630,  638,  642,  650,  658,  660,  662,  670,  678,
      680,  682,  690,  694,  702,   83,  154,  449,   96,  705,
      710,  714,  719,  728,  729,  737,  739,  740,  748,  751,

      759,  756,  767,  776,  775,  778,  779,  790,  793,  798,
      801,  812,   31,  813,  815,  817,  816,  831,  832,  842,
      840,  841,  843,  851,  852,  860,  861,  871,  869, 1013,
      880,  881,  870,  889,  890,  891,  906,  907,  908,  910,
      918,  922,  926,  927, 1013,  980,  985,  987,   59,  992,
      997, 1002, 1007
    } ;

static yyconst short int yy_def[254] =
    {   0,
      245,    1,  245,  245,  245,  245,  245,  246,  245,  245,
      245,  247,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  248,  248,
      248,  248,  248,  245,  245,  249,  248,  248,  248,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,  245,  245,  245,  245,  246,  245,  245,  245,
      245,  250,  251,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  249,   30,   39,  245,  249,   39,  249,
       39,  249,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
      245,  245,  250,  252,  251,  245,  245,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
      253,  245,  245,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,  253,  252,  245,  245,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,

       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,  245,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,   39,   39,   39,   39,   39,  245,
       39,   39,   39,   39,   39,   39,   39,   39,   39,   39,
       39,   39,   39,   39,    0,  245,  245,  245,  245,  245,
      245,  245,  245
    } ;

static yyconst short int yy_nxt[1075] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,    4,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   31,   44,   31,   45,   31,   31,   31,   46,   47,
       48,   49,   50,   51,   52,   31,   31,   31,   53,   54,
       55,   62,   78,  230,   76,   64,   63,   65,   66,   67,
       64,   76,   66,   66,   67,   68,   68,   96,   69,   70,
       68,   68,   64,   69,   67,   67,   67,   74,   74,   74,
       69,   69,   68,   68,  187,   75,   75,   74,   74,   74,

       77,   69,  188,   78,  189,   75,   75,   78,   78,   78,
       77,   76,  187,   78,   80,   80,   78,   70,   76,   82,
       77,   94,  153,   78,   95,   81,  188,   77,  189,   70,
       78,   82,   79,   82,   78,   78,  114,   78,   78,   78,
       76,   78,   78,   78,  114,   83,   77,  112,   76,   78,
       77,   58,   89,   78,   77,   76,   76,   78,   78,   78,
       78,   90,  114,   76,  111,  187,   91,  152,   92,   76,
      152,   77,   84,   85,   78,   86,   73,   93,   76,   76,
       76,   72,   87,   97,   71,   76,   76,   76,   88,   61,
       98,   76,   99,   76,   76,  100,   76,   76,  101,  112,

      102,  103,  104,   76,   76,   76,   59,   76,   76,   76,
       76,  105,   76,   76,  106,   76,   58,  108,   76,  107,
      110,  109,   60,  116,  116,  116,   76,   76,   64,   56,
       65,   66,   67,  245,   76,  245,  245,   60,   68,   68,
       76,   69,   70,   64,  245,   66,   66,   67,   64,  245,
       67,   67,   67,   68,   68,  245,   69,  245,   68,   68,
       68,   68,   68,   74,   74,   74,  245,  245,   68,   68,
       76,   74,   74,  117,  117,  117,   82,   76,   80,   80,
       80,   80,  118,   76,  245,   76,  245,  245,   83,   80,
      245,   81,   76,   76,  245,  245,   76,   76,   76,  245,

       76,   76,  119,   76,   76,  120,   76,  245,   76,   76,
       76,  122,  121,   76,   76,   76,   76,  245,   76,  245,
       76,  124,   76,   76,   76,  123,   76,   76,   76,   76,
      245,   76,   76,  125,   76,   76,  245,  245,   76,   76,
       76,  245,   76,  126,   76,  129,   76,   76,   76,  127,
       76,  245,  128,   76,   76,  245,  245,   76,  245,   76,
       76,  130,   76,   76,  131,   76,  245,  132,  245,   76,
       76,  245,   76,   76,  134,   76,  245,   76,   76,  245,
       76,  135,  133,   76,   76,   76,   76,  136,  245,   76,
      137,   76,   76,  142,  245,  140,   76,   76,  139,  245,

       76,  138,   76,   76,  245,  245,   76,   76,  143,  245,
       76,  144,  141,  245,   76,   76,   76,   76,  245,  245,
       76,  145,   76,  146,   76,  148,   76,  149,   76,  245,
       76,  147,  245,   76,  150,  116,  116,  116,   76,   76,
      154,   76,  156,   76,  245,   76,   76,  157,   76,   76,
       76,   76,  245,   76,  155,   76,   76,   76,  161,   76,
      245,  158,   76,  162,   76,   76,  213,  213,  213,   76,
       76,   76,   76,  159,  160,   76,  163,   76,  245,   76,
      166,  245,   76,  245,   76,   76,  165,   76,  164,   76,
       76,   76,   76,   76,   76,   76,   76,  245,   76,   76,

      245,   76,  245,   76,   76,  167,  168,   76,   76,   76,
       76,   76,   76,  171,  169,   76,  245,   76,   76,   76,
      172,   76,  170,   76,   76,   76,   76,   76,   76,  245,
      245,  245,  176,   76,   76,   76,   76,  245,   76,   76,
       76,   76,  174,   76,  173,   76,   76,   76,  175,   76,
       76,   76,  245,   76,   76,  177,  245,   76,   76,   76,
      181,   76,  180,   76,  178,   76,  245,  179,   76,  182,
       76,   76,  184,  183,   76,   76,  245,   76,  245,   76,
       76,  245,   76,   76,   76,   76,  245,   76,   76,   76,
      185,   76,  190,   76,   76,  245,   76,   76,  191,   76,

      245,   76,   76,   76,  245,  245,   76,   76,   76,  245,
       76,   76,   76,  245,  245,   76,   76,  245,   76,  193,
      192,   76,   76,   76,   76,  245,  194,   76,  245,   76,
       76,   76,  195,  245,   76,   76,   76,  245,   76,  245,
       76,   76,   76,   76,   76,  245,  196,  245,   76,   76,
       76,  245,   76,   76,   76,   76,   76,  245,  197,   76,
       76,  198,   76,  245,   76,   76,   76,  245,  245,   76,
      199,   76,   76,  245,  245,   76,   76,   76,  245,   76,
      200,  245,  245,   76,   76,   76,  245,  201,  203,   76,
      245,   76,   76,  202,   76,  245,   76,   76,  206,   76,

      245,   76,  205,   76,   76,  204,  207,   76,  245,   76,
      245,   76,   76,  245,   76,  208,   76,   76,  245,   76,
      245,   76,  210,   76,   76,   76,  209,   76,   76,   76,
      245,   76,  245,  245,  245,   76,   76,   76,  245,   76,
      212,   76,  245,   76,   76,  211,   76,  214,   76,   76,
      245,   76,   76,   76,  245,   76,  245,   76,  245,  245,
       76,   76,   76,   76,  245,  215,   76,  217,  245,   76,
       76,   76,  216,   76,   76,   76,   76,  219,   76,  245,
       76,   76,   76,  218,   76,   76,   76,   76,  245,   76,
       76,  245,   76,   76,  245,   76,  245,   76,   76,  245,

       76,   76,  220,   76,  222,  221,   76,  245,   76,   76,
       76,  224,   76,   76,   76,  223,   76,   76,  245,   76,
      226,  245,   76,   76,   76,   76,   76,   76,  227,  225,
      245,   76,   76,  245,   76,   76,  245,   76,  245,   76,
       76,  245,   76,  229,  228,   76,   76,   76,   76,   76,
       76,   76,  245,   76,   76,  245,   76,   76,   76,   76,
      231,  245,   76,   76,   76,   76,   76,  232,  233,  245,
      234,  245,   76,   76,   76,   76,   76,   76,   76,   76,
      235,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,  245,   76,   76,   76,   76,  245,  245,   76,   76,

      236,   76,   76,   76,   76,   76,  245,   76,   76,  237,
       76,   76,   76,  238,   76,   76,   76,   76,   76,  240,
      245,   76,   76,   76,   76,   76,  239,   76,   76,  245,
       76,   76,   76,  245,  244,  245,   76,   76,   76,  241,
       76,   76,   76,  242,   76,  243,  245,   76,   76,   76,
      245,   76,   76,   76,   76,   76,   76,   76,  245,   76,
       76,   76,  245,   76,  245,   76,  245,   76,   76,   76,
      245,  245,  245,   76,   76,  245,  245,  245,  245,   79,
       57,  245,   57,   57,   57,   60,  245,  245,   60,   60,
       76,   76,  113,  113,  113,  113,  113,  115,  245,  115,

      115,  115,  151,  151,  151,  151,  151,  186,  186,  186,
      186,  186,    3,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245
    } ;

static yyconst short int yy_chk[1075] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   20,  249,  213,   43,   21,   20,   21,   21,   21,
       22,   43,   22,   22,   22,   21,   21,   43,   21,   21,
       22,   22,   23,   22,   23,   23,   23,   29,   29,   29,
       69,   69,   23,   23,  186,   29,   29,   30,   30,   30,

       29,   69,  153,   29,  153,   30,   30,   31,   31,   31,
       30,   42,  151,   30,   32,   32,   32,   70,   42,   82,
       31,   42,  117,   31,   42,   32,  189,   32,  189,   70,
       32,   82,   30,   33,   33,   33,  113,   37,   37,   37,
       75,   38,   38,   38,   62,   33,   33,   60,   40,   33,
       37,   57,   40,   37,   38,   40,   41,   38,   39,   39,
       39,   40,  114,   41,   54,  187,   41,  114,   41,   41,
      187,   39,   37,   38,   39,   39,   28,   41,   44,   45,
       46,   27,   39,   44,   26,   44,   45,   46,   39,   12,
       44,   44,   45,   46,   48,   46,   47,   49,   46,   61,

       47,   48,   48,   47,   49,   50,   11,   48,   51,   47,
       49,   48,   50,   52,   48,   51,    8,   50,   50,   49,
       52,   51,   61,   64,   64,   64,   52,   76,   65,    7,
       65,   65,   65,    3,   76,    0,    0,   61,   65,   65,
       76,   65,   65,   66,    0,   66,   66,   66,   67,    0,
       67,   67,   67,   66,   66,    0,   66,    0,   67,   67,
       68,   68,   68,   74,   74,   74,    0,    0,   68,   68,
       79,   74,   74,   77,   77,   77,   83,   79,   80,   80,
       81,   81,   79,   79,    0,   84,    0,    0,   83,   80,
        0,   81,   84,   83,    0,    0,   86,   81,   84,    0,

       83,   85,   84,   86,   81,   85,   83,    0,   85,   86,
       81,   87,   86,   88,   85,   90,   89,    0,   87,    0,
       88,   89,   90,   89,   87,   88,   88,   91,   90,   89,
        0,   92,   94,   90,   91,   93,    0,    0,   92,   94,
       91,    0,   93,   91,   92,   94,   95,   96,   93,   92,
       97,    0,   93,   95,   96,    0,    0,   97,    0,   95,
       96,   95,   99,   97,   96,   98,    0,   98,    0,   99,
      101,    0,   98,  100,   99,   99,    0,  101,   98,    0,
      100,  100,   98,  101,  102,  103,  100,  101,    0,  104,
      102,  102,  103,  105,    0,  104,  104,  102,  103,    0,

      105,  102,  104,  106,    0,    0,  105,  107,  105,    0,
      106,  106,  104,    0,  107,  108,  106,  109,    0,    0,
      107,  107,  108,  108,  109,  109,  110,  109,  108,    0,
      109,  108,    0,  110,  110,  116,  116,  116,  118,  110,
      118,  119,  120,  121,    0,  118,  122,  121,  119,  120,
      121,  118,    0,  122,  119,  120,  121,  123,  124,  122,
        0,  122,  125,  125,  123,  124,  188,  188,  188,  125,
      123,  124,  126,  123,  123,  125,  126,  127,    0,  126,
      129,    0,  128,    0,  127,  126,  128,  129,  127,  128,
      127,  130,  131,  129,  133,  128,  132,    0,  130,  131,

        0,  133,    0,  132,  130,  131,  132,  133,  134,  132,
      135,  136,  137,  136,  134,  134,    0,  135,  136,  137,
      137,  134,  135,  135,  136,  137,  138,  139,  141,    0,
        0,    0,  141,  138,  139,  141,  140,    0,  142,  138,
      139,  141,  139,  140,  138,  142,  143,  146,  140,  140,
      144,  142,    0,  143,  146,  142,    0,  144,  145,  143,
      146,  147,  145,  144,  143,  145,    0,  144,  147,  147,
      148,  145,  149,  148,  147,  154,    0,  148,    0,  149,
      150,    0,  154,  148,  155,  149,    0,  150,  154,  156,
      150,  155,  154,  150,  157,    0,  156,  155,  156,  158,

        0,  157,  156,  159,    0,    0,  158,  157,  161,    0,
      159,  160,  158,    0,    0,  161,  159,    0,  160,  160,
      159,  161,  162,  163,  160,    0,  161,  164,    0,  162,
      163,  165,  162,    0,  164,  162,  163,    0,  165,    0,
      164,  166,  167,  168,  165,    0,  165,    0,  166,  167,
      168,    0,  169,  170,  166,  167,  168,    0,  166,  169,
      170,  168,  171,    0,  172,  169,  170,    0,    0,  171,
      170,  172,  173,    0,    0,  171,  174,  172,    0,  173,
      172,    0,    0,  174,  175,  173,    0,  173,  175,  174,
        0,  175,  176,  174,  177,    0,  178,  175,  178,  176,

        0,  177,  177,  178,  179,  176,  179,  177,    0,  178,
        0,  179,  180,    0,  181,  180,  182,  179,    0,  180,
        0,  181,  182,  182,  183,  180,  181,  181,  184,  182,
        0,  183,    0,    0,    0,  184,  185,  183,    0,  190,
      185,  184,    0,  185,  191,  184,  190,  190,  192,  185,
        0,  191,  190,  193,    0,  192,    0,  191,    0,    0,
      193,  192,  194,  195,    0,  193,  193,  195,    0,  194,
      195,  196,  194,  197,  198,  194,  195,  198,  196,    0,
      197,  198,  199,  196,  196,  200,  197,  198,    0,  199,
      202,    0,  200,  201,    0,  199,    0,  202,  200,    0,

      201,  203,  200,  202,  203,  201,  201,    0,  203,  205,
      204,  205,  206,  207,  203,  204,  205,  204,    0,  206,
      207,    0,  205,  204,  208,  206,  207,  209,  208,  206,
        0,  208,  210,    0,  209,  211,    0,  208,    0,  210,
      209,    0,  211,  211,  210,  210,  212,  214,  211,  215,
      217,  216,    0,  212,  214,    0,  215,  217,  216,  212,
      214,    0,  215,  217,  216,  218,  219,  215,  216,    0,
      219,    0,  218,  219,  221,  222,  220,  223,  218,  219,
      220,  221,  222,  220,  223,  224,  225,  221,  222,  220,
      223,    0,  224,  225,  226,  227,    0,    0,  224,  225,

      227,  226,  227,  229,  233,  228,    0,  226,  227,  228,
      229,  233,  228,  229,  231,  232,  229,  233,  228,  232,
        0,  231,  232,  234,  235,  236,  231,  231,  232,    0,
      234,  235,  236,    0,  239,    0,  234,  235,  236,  235,
      237,  238,  239,  237,  240,  238,    0,  237,  238,  239,
        0,  240,  241,  237,  238,  239,  242,  240,    0,  241,
      243,  244,    0,  242,    0,  241,    0,  243,  244,  242,
        0,    0,    0,  243,  244,    0,    0,    0,    0,  244,
      246,    0,  246,  246,  246,  247,    0,    0,  247,  247,
      248,  248,  250,  250,  250,  250,  250,  251,    0,  251,

      251,  251,  252,  252,  252,  252,  252,  253,  253,  253,
      253,  253,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "AnalisadorLexicoC.l"
#define INITIAL 0
#line 2 "AnalisadorLexicoC.l"

#include<stdio.h>
#include<stdlib.h>
int Upper=0;
int Lower=0;
#line 689 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 17 "AnalisadorLexicoC.l"


#line 843 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1013 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 19 "AnalisadorLexicoC.l"
{ printf("Operador de adicao: [%s]\t" , yytext)	    ;};
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "AnalisadorLexicoC.l"
{ printf("Operador de subtracao: [%s]\t", yytext)	    ;};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "AnalisadorLexicoC.l"
{ printf("Operador de multiplicacao: [%s]\t", yytext)	    ;};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "AnalisadorLexicoC.l"
{ printf("Operador de divisao: [%s]\t", yytext)	    ;};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "AnalisadorLexicoC.l"
{ printf("Operador de modulo: [%s]\t", yytext)	    ;};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "AnalisadorLexicoC.l"
{ printf("Operador not: [%s]\t", yytext)	    ;};
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "AnalisadorLexicoC.l"
{ printf("Operador and: [%s]\t", yytext)	    ;};
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "AnalisadorLexicoC.l"
{ printf("Operador or: [%s]\t", yytext)	    ;};
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "AnalisadorLexicoC.l"
{ printf("Operador notequal: [%s]\t", yytext)	    ;};
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "AnalisadorLexicoC.l"
{ printf("Operador equal: [%s]\t", yytext)	    ;};
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "AnalisadorLexicoC.l"
{ printf("Operador assign: [%s]\t", yytext)	    ;};
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "AnalisadorLexicoC.l"
{ printf("Operador less: [%s]\t", yytext)	    ;};
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "AnalisadorLexicoC.l"
{ printf("Operador greater: [%s]\t", yytext)	    ;};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "AnalisadorLexicoC.l"
{ printf("Operador lessequal: [%s]\t", yytext)    ;};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "AnalisadorLexicoC.l"
{ printf("Operador greaterequal: [%s]\t", yytext) ;};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "AnalisadorLexicoC.l"
{ printf("NumberSign: [%s]\t", yytext)	  ;};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "AnalisadorLexicoC.l"
{ printf("Endereco de memoria: [%s]\t", yytext)  ;};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "AnalisadorLexicoC.l"
{ printf("Parentese esquerdo: [%s]\t", yytext)	  ;};
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "AnalisadorLexicoC.l"
{ printf("Parentese direito: [%s]\t", yytext)	  ;};
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "AnalisadorLexicoC.l"
{ printf("Chave esquerda: [%s]\t", yytext)	  ;};
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "AnalisadorLexicoC.l"
{ printf("Chave direita: [%s]\t", yytext)	  ;};
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "AnalisadorLexicoC.l"
{ printf("Cochete esquerdo: [%s]\t", yytext)	  ;};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "AnalisadorLexicoC.l"
{ printf("Cochete direito: [%s]\t", yytext)  ;};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "AnalisadorLexicoC.l"
{ printf("Ponto e virdula: [%s]\t", yytext)	  ;};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "AnalisadorLexicoC.l"
{ printf("Virgula: [%s]\t", yytext)	  ;};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "AnalisadorLexicoC.l"
{ printf("Ponto: [%s]\t", yytext)		  ;};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "AnalisadorLexicoC.l"
{ printf("Aspas simples: [%s]\t", yytext)	  ;};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "AnalisadorLexicoC.l"
{ printf("Dois pontos: [%s]\t", yytext)	  ;};
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "AnalisadorLexicoC.l"
{ printf("Keyword auto: [%s]\t", yytext)  ;};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "AnalisadorLexicoC.l"
{ printf("Keyword break: [%s]\t", yytext)  ;};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "AnalisadorLexicoC.l"
{ printf("Keyword case: [%s]\t", yytext)  ;};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "AnalisadorLexicoC.l"
{ printf("Keyword char: [%s]\t", yytext)  ;};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "AnalisadorLexicoC.l"
{ printf("Keyword const: [%s]\t", yytext)  ;};
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "AnalisadorLexicoC.l"
{ printf("Keyword continue: [%s]\t", yytext)  ;};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "AnalisadorLexicoC.l"
{ printf("Keyword default: [%s]\t", yytext)  ;};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "AnalisadorLexicoC.l"
{ printf("Keyword do: [%s]\t", yytext)  ;};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "AnalisadorLexicoC.l"
{ printf("Keyword double: [%s]\t", yytext)  ;};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "AnalisadorLexicoC.l"
{ printf("Keyword else: [%s]\t", yytext)     ;};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "AnalisadorLexicoC.l"
{ printf("Keyword enum: [%s]\t", yytext)  ;};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "AnalisadorLexicoC.l"
{ printf("Keyword extern: [%s]\t", yytext)  ;};
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "AnalisadorLexicoC.l"
{ printf("Keyword float: [%s]\t", yytext)  ;};
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "AnalisadorLexicoC.l"
{ printf("Keyword for: [%s]\t", yytext)  ;};
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "AnalisadorLexicoC.l"
{ printf("Keyword goto: [%s]\t", yytext)  ;};
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "AnalisadorLexicoC.l"
{ printf("Keyword if: [%s]\t", yytext)       ;};
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "AnalisadorLexicoC.l"
{ printf("Keyword int: [%s]\t", yytext)  ;};
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "AnalisadorLexicoC.l"
{ printf("Keyword long: [%s]\t", yytext)  ;};
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "AnalisadorLexicoC.l"
{ printf("Keyword register: [%s]\t", yytext)  ;};
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "AnalisadorLexicoC.l"
{ printf("Keyword return: [%s]\t", yytext)  ;};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "AnalisadorLexicoC.l"
{ printf("Keyword short: [%s]\t", yytext)  ;};
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "AnalisadorLexicoC.l"
{ printf("Keyword signed: [%s]\t", yytext)  ;};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "AnalisadorLexicoC.l"
{ printf("Keyword sizeof: [%s]\t", yytext)  ;};
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "AnalisadorLexicoC.l"
{ printf("Keyword static: [%s]\t", yytext)  ;};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "AnalisadorLexicoC.l"
{ printf("Keyword struct: [%s]\t", yytext)  ;};
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "AnalisadorLexicoC.l"
{ printf("Keyword switch: [%s]\t", yytext)  ;};
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "AnalisadorLexicoC.l"
{ printf("Keyword typedef: [%s]\t", yytext)  ;};
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "AnalisadorLexicoC.l"
{ printf("Keyword union: [%s]\t", yytext)  ;};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "AnalisadorLexicoC.l"
{ printf("Keyword unsigned: [%s]\t", yytext)  ;};
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "AnalisadorLexicoC.l"
{ printf("Keyword void: [%s]\t", yytext)  ;};
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "AnalisadorLexicoC.l"
{ printf("Keyword volatile: [%s]\t", yytext)  ;};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "AnalisadorLexicoC.l"
{ printf("Keyword while: [%s]\t", yytext)  ;};
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 81 "AnalisadorLexicoC.l"
{ printf("Keyword print: [%s]\t", yytext)    ;};
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 82 "AnalisadorLexicoC.l"
{ printf("Keyword putc: [%s]\t", yytext)     ;};
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 83 "AnalisadorLexicoC.l"
{ printf("Keyword include: [%s]\t", yytext)  ;};
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 84 "AnalisadorLexicoC.l"
{ printf("Keyword Function: [%s]\t", yytext)  ;};
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "AnalisadorLexicoC.l"
{ printf("Letra(s)/Palavra: [%s]>\t", yytext) ;};
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "AnalisadorLexicoC.l"
{ printf("Integer: [%s]\t", yytext)    ;};
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "AnalisadorLexicoC.l"
{ printf("Real: [%s]\t", yytext) ;};
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "AnalisadorLexicoC.l"
{ printf("Hexadecimal: [%s]\t", yytext) ;};
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "AnalisadorLexicoC.l"
{ printf("Octal: [%s]\t", yytext) ;};
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "AnalisadorLexicoC.l"
{ printf("Binario: [%s]\t", yytext) ;};
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "AnalisadorLexicoC.l"
{ printf("Identificador: [%s]\t", yytext) ;};
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "AnalisadorLexicoC.l"
{ printf("Vetor: [%s]\t", yytext) ;};
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 95 "AnalisadorLexicoC.l"
{ printf("Matriz: [%s]\t", yytext) ;};
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 98 "AnalisadorLexicoC.l"
{ printf("Char: [%s]\t", yytext)	      ;};
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 99 "AnalisadorLexicoC.l"
{ printf("String: [%s]\t", yytext)     ;};
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 101 "AnalisadorLexicoC.l"
{ /* DO NOTHING  */ }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 102 "AnalisadorLexicoC.l"
{ printf("Comentario: [%s]", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 103 "AnalisadorLexicoC.l"
{ printf("Comentario: [%s]", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 104 "AnalisadorLexicoC.l"
{ printf("Comentario indeterminado: [%s]", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 105 "AnalisadorLexicoC.l"
{ printf("Aspas duplas indeterminada: [%s]", yytext)  ; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 106 "AnalisadorLexicoC.l"
{ printf("Caractere desconhecido: [%s]",yytext)   ;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 107 "AnalisadorLexicoC.l"
ECHO;
	YY_BREAK
#line 1336 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 245);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 107 "AnalisadorLexicoC.l"


int yywrap()
{
return 1;
}

int main()
{



yylex();


return 0;
system("PAUSE");

}
